name: Publish Package to npmjs

on:
  release:
    types: [published]

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  token: ${{secrets.NPM_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'
          registry-url: 'https://registry.npmjs.org'
          scope: '@seedz-d2f'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Publish
        run: npm publish --access public
