name: Publish Package to npmjs

on:
  push:
    branches:
      - master

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  token: ${{secrets.NPM_TOKEN}}
  V_NPM_TOEKN: ${{vars.V_NPM_TOEKN}}

jobs:
  publish:
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'

      - name: Install dependencies
        run: yarn

      - name: PRINT
        run: echo "NPM_TOKEN- $NPM_TOKEN"

      - name: PRINT 2
        run: echo "V_NPM_TOEKN- $V_NPM_TOEKN"

      - name: PRINT 3
        run: echo "SECRET_NPM_TOKEN- ${{secrets.NPM_TOKEN}}"

      - name: PRINT 4
        run: echo "VAR_V_NPM_TOEKN- ${{vars.V_NPM_TOEKN}}"

      - name: Build project
        run: yarn build

      - name: Publish
        run: npm publish --access public
