name: publish-ci

on:
  release:
    types: [published]

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  publish:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Publish
        run: npm publish --access public
