name: typescript-ci

on:
  pull_request:
    branches:
      - '**'

jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Run type:check
        run: yarn type:check
